---
output: pdf_document
---

\thispagestyle{empty}

# Installation instructions for R, RStudio^[Document compiled by [Marcel Neunhoeffer](https://www.marcel-neunhoeffer.com/) and [Oliver Rittmann](https://www.sowi.uni-mannheim.de/gschwend/team/postdocs-and-doctoral-students/oliver-rittmann/).] 

## What is `R`?

`R` is a programming language designed to help you perform statistical analysis, create graphics, and later on write your own statistical software. `R` is becoming increasingly popular and knowledge of `R` will help you in the job market. `R` is probably the most versatile statistical tool out there (and its free and open source so you can literally use it anywhere).

## What is RStudio?

RStudio is very good graphical user interface for `R` and will be the program which we will use during the lab sessions. In recent years a growing number of features have been added to this graphical user interface, which makes it the preferred choice for learning `R` especially among beginners.


## Installing R and RStudio

### a) Instructions for Windows users

1. Install R
    1. Open your browser and go to [https://cran.rstudio.com](https://cran.rstudio.com).
    2. Click on "Download R for Windows".
    3. Click on "base".
    4. Click "Download R-4.2.1 for Windows" and save the executable file on your computer.
    5. Run the .exe file and follow the installation instructions.
    6. Now that R is installed, you need to download and install RStudio.
    
2. Install RStudio
    1. Go to [www.rstudio.com](www.rstudio.com) and click on the "Download" button on the top bar.
    2. Scroll down and click on the "Download" button for the free RStudio Desktop version.
    3. Click on "Download RStudio for Windows" and save the executable file on your computer.
    4. Run the .exe file and follow the installation instructions.


### b) Instructions for Mac users

1. Install R
    1. Open your browser and go to [https://cran.rstudio.com](https://cran.rstudio.com).
    2. Click on "Download R for (Mac) OS X".
    3. Click on "R-4.2.1.pkg" and save the file on your computer.
    4. Run the .pkg file and follow the installation instructions.
    5. Now that R is installed, you need to download and install RStudio.

2. Install RStudio
    1. Go to [www.rstudio.com](www.rstudio.com) and click on the "Download" button on the top bar.
    2. Scroll down and click on the "Download" button for the free RStudio Desktop version.
    3. Click on "Download RStudio for Mac" and save the .dmg file on your computer.
    4. Double-click on the .dmg file to open it and drag and drop the RStudio Icon to your applications folder.
    
Or check out the following two videos:

- [Installing R](https://vimeo.com/203516510)

- [Installing RStudio](https://vimeo.com/203516968)

If you already have installed R and RStudio on your computer, make sure to check whether you have the most recent versions and update if necessary.
